blank_issues_enabled: false
contact_links:
  - name: "❓ Ask a Question or Suggest a Feature"
    url: "https://github.com/hadoooooouken/qimgv-plus/discussions"
    about: "Please use GitHub Discussions for questions, ideas, and feature requests."
