#pragma once

enum SortingMode {
  SORT_NAME,
  SORT_NAME_DESC,
  SORT_SIZE,
  SORT_SIZE_DESC,
  SORT_TIME,
  SORT_TIME_DESC
};

enum ImageFitMode {
  FIT_WINDOW,
  FIT_WIDTH,
  FIT_ORIGINAL,
  FIT_WINDOW_STRETCH,
  FIT_FREE
};

enum PanelPosition { PANEL_TOP, PANEL_BOTTOM, PANEL_LEFT, PANEL_RIGHT };

enum ScalingFilter {
  QI_FILTER_NEAREST,
  QI_FILTER_BILINEAR,
  QI_FILTER_SMART,
  QI_FILTER_CAS,
  QI_FILTER_SMART_GPU
};

enum ZoomIndicatorMode {
  INDICATOR_DISABLED,
  INDICATOR_ENABLED,
  INDICATOR_AUTO
};

enum DefaultCropAction { ACTION_CROP, ACTION_CROP_SAVE };

enum ImageFocusPoint { FOCUS_TOP, FOCUS_CENTER, FOCUS_CURSOR };

enum ImageScrolling {
  SCROLL_NONE,
  SCROLL_BY_TRACKPAD,
  SCROLL_BY_TRACKPAD_AND_WHEEL
};

enum ViewMode { MODE_DOCUMENT, MODE_FOLDERVIEW };

enum FolderEndAction {
  FOLDER_END_NO_ACTION,
  FOLDER_END_LOOP,
  FOLDER_END_GOTO_ADJACENT
};

enum ThumbPanelStyle { TH_PANEL_SIMPLE, TH_PANEL_EXTENDED };

enum ThemeMode { THEME_AUTO, THEME_DARK, THEME_LIGHT };
